# Generated by Django 5.1.3 on 2025-01-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
